title: Redlii
email: redlii@redlli.com
description: >- # this means to ignore newlines until "baseurl:"
  official page redlii.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redlii.com/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  redlli

# SEO Settings
seo:
  title: "Redlii"
  description: "Welcome to Wounderland"
  keywords: "redlii, the3dmaker, TKiD, Animar, JA by redlii"
  image: "/assets/images/cover.jpg"
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
